linters:
  enable:
    - bodyclose
    - errcheck
    - exportloopref
    - dupl
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - govet
    - lll
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-use-default: false
